# Generated by Django 2.1.2 on 2018-11-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oferty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wypozyczalnia',
            name='adres',
            field=models.CharField(default='Lotnisko', max_length=100),
        ),
    ]
