# Generated by Django 2.1.2 on 2018-11-27 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oferty', '0002_wypozyczalnia_adres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samochod',
            name='rodzaj_paliwa',
            field=models.CharField(default='Ropa', max_length=50),
        ),
    ]
