# Generated by Django 2.1.2 on 2018-12-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oferty', '0004_samochod_ilosc_miejsc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wypozazenie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(default='GPS', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='samochod',
            name='wypozazenie',
            field=models.ManyToManyField(blank=True, to='oferty.Wypozazenie'),
        ),
    ]
