# Generated by Django 2.1.2 on 2018-12-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oferty', '0005_auto_20181209_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='samochod',
            name='wypozazenie',
        ),
        migrations.AddField(
            model_name='samochod',
            name='ilosc_drzwi',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='samochod',
            name='klimatyzacja',
            field=models.CharField(default='Brak', max_length=50),
        ),
        migrations.AddField(
            model_name='samochod',
            name='walizki',
            field=models.IntegerField(default=2),
        ),
        migrations.DeleteModel(
            name='Wypozazenie',
        ),
    ]
