# Generated by Django 2.1.2 on 2018-12-09 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oferty', '0006_auto_20181209_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='samochod',
            name='skrzynia_biegow',
            field=models.CharField(default='Automat', max_length=50),
        ),
    ]
