# Generated by Django 2.1.2 on 2019-01-15 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oferty', '0007_samochod_skrzynia_biegow'),
    ]

    operations = [
        migrations.AddField(
            model_name='samochod',
            name='zdjecie',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
