# Generated by Django 2.1.2 on 2018-12-08 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oferty', '0004_samochod_ilosc_miejsc'),
        ('stronaGlowna', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfertyStronaGlownaOsobowe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('samochody', models.ManyToManyField(to='oferty.Samochod')),
            ],
        ),
        migrations.CreateModel(
            name='OfertyStronaGlownaWieksze',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('samochody', models.ManyToManyField(to='oferty.Samochod')),
            ],
        ),
    ]
