# Generated by Django 2.1.2 on 2018-11-27 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zlozZamowienie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zamowienie',
            name='id_samochodu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oferty.Samochod'),
        ),
        migrations.AlterField(
            model_name='zamowienie',
            name='id_ubezpieczenia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zlozZamowienie.Ubezpieczenie'),
        ),
        migrations.AlterField(
            model_name='zamowienie',
            name='kupujacy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
