# Generated by Django 2.1.2 on 2018-11-27 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zlozZamowienie', '0002_auto_20181127_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zamowienie',
            name='dodatki',
            field=models.ManyToManyField(blank=True, to='zlozZamowienie.Dodadek'),
        ),
    ]
